import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashSet;

/**
 * Distinct powers
Problem 29

Consider all integer combinations of ab for 2 <= a <= 5 and 2 <= b <= 5:

    22=4, 23=8, 24=16, 25=32
    32=9, 33=27, 34=81, 35=243
    42=16, 43=64, 44=256, 45=1024
    52=25, 53=125, 54=625, 55=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100?

 */

/**
 * @author p541832
 *
 */
public class Prob_29 {

	/**
	 * 
	 */
	public Prob_29() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		BigInteger value = BigInteger.ONE;
		BigInteger aValue = null;
		ArrayList<BigInteger> valueList = new ArrayList<BigInteger>();
		
		for(int a=2;a<=100;a++){
			for(int b=2;b<=100;b++){
				aValue = new BigInteger(String.valueOf(a));
				value = aValue.pow(b);
				valueList.add(value);
			}
		}
		HashSet<BigInteger> hs=new HashSet<>(valueList);
		System.out.println(valueList.size());//9801
		System.out.println(hs.size());//9183
	}

}
