import java.util.ArrayList;


/**
 * Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?

 */

/**
 * @author p541832
 *
 */
public class Prob_44 {

	/**
	 * 
	 */
	public Prob_44() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		ArrayList<Long> pentNums = new ArrayList<Long>();
		for(long i=0;i<10000000L;i++){
			if(PentagonalNum(i))
				pentNums.add(i);
			//	System.out.println(i);
		}
		
		for(int j=0;j<pentNums.size();j++){
			for(int k=0;k<pentNums.size();k++){
				if(pentNums.contains(Math.abs(pentNums.get(j)-pentNums.get(k))) && pentNums.contains((pentNums.get(j)+pentNums.get(k))))
						System.out.println(pentNums.get(j)-pentNums.get(k));//5482660
			}
		}
		
	}

	private static boolean PentagonalNum(long i) {
		// TODO Auto-generated method stub
		double x = (Math.sqrt((24*i)+1)+1)/6;
		if(x%1==0)
		return true;
		return false;
	}

}
